### ISSUE TITLE
mutableComparisonSamplers is unclear

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/Vulkan-Portability#15]
If the Vulkan implementation does not allow descriptors with comparison samplers to be updated, then how can comparison samplers be used at all?  The only way to populate a descriptor in Vulkan is with vkUpdateDescriptorSets.

**Comment by danginsburg** [comment]
You have to use an immutable sampler in this case.  See VkDescriptorSetLayoutBinding.pImmutableSamplers.
