### ISSUE TITLE
Spec. too strict about `VK_COMPONENT_SWIZZLE_IDENTITY`

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/Vulkan-Portability#27]
According to the `VUID-VkImageViewCreateInfo-imageViewFormatSwizzle-04465`, component swizzle must be set to `VK_COMPONENT_SWIZZLE_IDENTITY` when swizzle is not available in the portability device. This is way too strict and forces changing perfectly good code that is setting up an identity swizzle in other ways, e.g.

```
        colorAttachmentView.components = {
            VK_COMPONENT_SWIZZLE_R,
            VK_COMPONENT_SWIZZLE_G,
            VK_COMPONENT_SWIZZLE_B,
            VK_COMPONENT_SWIZZLE_A
        };
```

I had this in both my swapchain and text overlay set up code. The origin of this code was Willems' Vulkan samples. God only know ow many places he has or will have to change because of this.

I'm filing this here because according to the VUID this is what the spec says. If it is just the validation layer that is being too strict let me know.

**Comment by sfricke-samsung** [comment]
So a while ago I worked with both the validation layers, spec, and CTS to finally make sure the other VUs related say

> must have the [identity swizzle](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#resources-image-views-identity-mappings)

And confirmed that `identity swizzle` did not mean "only" `VK_COMPONENT_SWIZZLE_IDENTITY ` but also allow the other values mapped in 

![image](https://user-images.githubusercontent.com/46493288/119161409-26e85180-ba0e-11eb-8e94-e98332cf6271.png)

So I am curious if `VUID-VkImageViewCreateInfo-imageViewFormatSwizzle-04465` (which was written after I made the other changes) made a mistake of not using the reference to the table

**Comment by MarkCallow** [comment]
Just by the language of the VUID which explicitly mentions `VK_COMPONENT_SWIZZLE_IDENTITY` yes it looks like the VUID is not referencing the table.

**Comment by ncesario-lunarg** [comment]
The validation layers check is from my interpretation of the VUID, which I did read to mean _only_ `VK_COMPONENT_SWIZZLE_IDENTITY`. If that is indeed incorrect, I added https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2904 to address it.

**Comment by sfricke-samsung** [comment]
I created an internal spec change a while ago that would fix this, just waiting to get approved

https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4600

**Comment by sfricke-samsung** [comment]
in 1.x.185 spec, `VUID-VkImageViewCreateInfo-imageViewFormatSwizzle-04465` was updated to relax swizzle language, closing unless anything else further is needed
