### ISSUE TITLE
Add VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderSpecConstantOpCompositeInsert capability

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Portability#40]
Some CTS tests fail when the shader uses `OpCompositeInsert` when presenting a spec constant. 

This may be fixable with extensive changes to the way SPIRV-Cross outputs spec constant customizations, doing so using text-replacement placeholders, etc.

These use cases can be disabled in CTS and reported as Not Supported, by adding a `VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderSpecConstantOpCompositeInsert` capability.

This affects 5 CTS tests:

```
dEQP-VK.spirv_assembly.instruction.compute.opspecconstantop.vector_related
dEQP-VK.spirv_assembly.instruction.graphics.opspecconstantop.vector_related_vert
dEQP-VK.spirv_assembly.instruction.graphics.opspecconstantop.vector_related_tessc
dEQP-VK.spirv_assembly.instruction.graphics.opspecconstantop.vector_related_tesse
dEQP-VK.spirv_assembly.instruction.graphics.opspecconstantop.vector_related_frag
  MSL conversion error: OpCompositeInsert spec constant op is not supported.
```

**Comment by cdavis5e** [comment]
Now that I've implemented this in SPIRV-Cross, we don't need this flag anymore.
