### ISSUE TITLE
Add VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderSPIRVAssemblyConformance capability

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Portability#41]
Some CTS tests fail when the shader uses edge cases built with customized SPIR-V assembled outside GLSL. 

This is likely fixable with effort within the implementations.

In the meantime, these use cases can be disabled in CTS and reported as Not Supported, by adding a `VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderSPIRVAssemblyConformance` capability.

This affects 5 CTS tests:

```
dEQP-VK.spirv_assembly.instruction.compute.opundef.undefined_constant_composite
dEQP-VK.spirv_assembly.instruction.compute.opundef.undefined_spec_constant_composite
  Bad cast
  
dEQP-VK.spirv_assembly.instruction.compute.signed_op.uint_smulextended
  Fail

dEQP-VK.spirv_assembly.instruction.compute.empty_struct.copying.copy_object_ubo
dEQP-VK.spirv_assembly.instruction.compute.empty_struct.copying.copy_object_ssbo
  MSL syntax errors
```

~~`dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_vert`
`dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_vert`
`dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_vert`
`dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_frag`
`   MSL type errors`
`dEQP-VK.spirv_assembly.instruction.compute.decoration_group.all`
`   MSL syntax errors`~~

**Comment by kvark** [comment]
This flag seems very vague and non-actionable by the users.

**Comment by billhollings** [comment]
Potential SPRIV-Cross fix for the final four errors in the list above can be found [here](https://github.com/KhronosGroup/SPIRV-Cross/issues/1763).

**Comment by billhollings** [comment]
[SPIRV-Cross PR #1897](https://github.com/KhronosGroup/SPIRV-Cross/pull/1897) fixed the following CTS failures:

```
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_vert
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_vert
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_vert
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_frag
  MSL type errors
```

**Comment by cdavis5e** [comment]
[SPIRV-Cross PR #2044](/KhronosGroup/SPIRV-Cross/pull/2044) fixed one more:

```
dEQP-VK.spirv_assembly.instruction.compute.decoration_group.all
  MSL syntax errors
```

Apparently, that test was using `restrict`.

**Comment by cdavis5e** [comment]
The remaining issues have been fixed in SPIRV-Cross.
