### ISSUE TITLE
Add VkPhysicalDevicePortabilitySubsetFeaturesKHR:: depthClampDeltaOneBiasClampNegative capability

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Portability#46]
Some CTS tests fail when using depth clamp with a large negative bias.

This might be fixable with effort within the implementations.

In the meantime, these use cases can be disabled in CTS and reported as Not Supported, by adding a `VkPhysicalDevicePortabilitySubsetFeaturesKHR:: depthClampDeltaOneBiasClampNegative` capability.

This affects 1 CTS tests:

```
dEQP-VK.draw.renderpass.inverted_depth_ranges.depthclamp_deltaone_bias_clamp_neg
  Fail (Result images are incorrect)
```

**Comment by kvark** [comment]
How do you define "large" for the purpose of this flag?
Or is it meant to forbid any negative bias for the depth?

**Comment by cdavis5e** [comment]
This looks like another depth accuracy issue. The result and reference images are completely indistinguishable even to my discerning eyes. The error mask shows a faint line toward the end of the triangle where the result depth isn't quite close enough to the reference. I recommend we ask for a threshold widening or a waiver for this one.

**Comment by alyssarosenzweig** [comment]
Filed https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/5079

**Comment by billhollings** [comment]
> Filed https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/5079

Thanks!

**Comment by theFJ1991** [comment]
F J XROn 13 Apr 2024, at 2:56 AM, Alyssa Rosenzweig ***@***.***> wrote:﻿
Filed https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/5079

**Comment by alyssarosenzweig** [comment]
Fix merged into CTS, this can be closed

**Comment by billhollings** [comment]
> Fix merged into CTS, this can be closed

Thank you!
