### ISSUE TITLE
Add VkPhysicalDevicePortabilitySubsetFeaturesKHR:: depthClampMultipleViewport capability

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Portability#47]
Some CTS tests fail when using depth clamp with multiple viewports.

This might be fixable with effort within the implementations.

In the meantime, these use cases can be disabled in CTS and reported as Not Supported, by adding a `VkPhysicalDevicePortabilitySubsetFeaturesKHR:: depthClampMultipleViewport` capability.

This affects 2 CTS tests:

```
dEQP-VK.draw.renderpass.depth_clamp.d32_sfloat_clamp_four_viewports'..
dEQP-VK.draw.renderpass.depth_clamp.d32_sfloat_s8_uint_clamp_four_viewports'..
  Fail (Depth value mismatch, expected: 1, got: 0.5 at (128, 0, 0))
```

**Comment by kvark** [comment]
A Vulkan-1.0 portability implementation doesn't have to support multiple viewports, if I remember correctly.
So it may be conformant without this flag.

**Comment by cdavis5e** [comment]
The tests no longer run and are now marked `NotSupported` because they now require the `geometryShader` feature.
