### ISSUE TITLE
Add VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderDuplicateSpecId capability

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Portability#48]
Some CTS tests fail when using depth clamp with duplicate specialization constant SpecIds.

This might be fixable with effort within the implementations.

In the meantime, these use cases can be disabled in CTS and reported as Not Supported, by adding a `VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderDuplicateSpecId` capability.

This affects 3 CTS tests:

```
dEQP-VK.compute.basic.max_local_size_x
dEQP-VK.compute.basic.max_local_size_y
dEQP-VK.compute.basic.max_local_size_z
  Fail (vk.createComputePipelines(device, pipelineCache, 1u, pCreateInfo, pAllocator, &object): VK_ERROR_INVALID_SHADER_NV at vkRefUtil.cpp:49)
```

**Comment by kvark** [comment]
What does depth clamping have to do with specialization constants?

**Comment by cdavis5e** [comment]
This has been fixed in SPIRV-Cross.
