### ISSUE TITLE
Add VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderEarlyFragmentTestDiscardNoTestsStencil capability

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Portability#52]
Some CTS tests fail when using early fragment discard tests on a stencil.

This might be fixable with effort within the implementations.

In the meantime, these use cases can be disabled in CTS and reported as Not Supported, by adding a `VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderEarlyFragmentTestDiscardNoTestsStencil ` capability.

This affects 1 CTS tests:

```
dEQP-VK.fragment_operations.early_fragment.discard_no_early_fragment_tests_stencil
  Fail (Rendered stencil value [ 16, 0, 0] is not correct: 4 != 3 at vktFragmentOperationsEarlyFragmentTests.cpp:834)
```

**Comment by cdavis5e** [comment]
So this one is a result of Metal not allowing fragment shader writes to depth when there's no depth attachment. The store is thus dummied out in the generated MSL shader. The problem is that the test relies on a side effect of the write, namely, that late fragment tests are forced. But because there's no depth attachment and thus no real write to depth, Metal thinks it can get away with early fragment tests, so the stencil is incorrectly updated and the test fails.

**Comment by billhollings** [comment]
Thanks for such determined research.

How do you recommend we approach this? 

- Error in CTS (relying on a side-effect) that should be corrected there?
- Unintended looseness in the Vulkan spec that can be tightened up (and then rolled into a CTS fix)?
- Some form of portability `VkPhysicalDevicePortabilitySubsetFeaturesKHR` flag?

**Comment by cdavis5e** [comment]
The test first initializes the stencil to 3, then clears half of it to 1. The `pass` and `stencilFail` stencil ops are set to `INCREMENT_CLAMP`, so if the depth/stencil tests are working the way Vulkan says they should, the halves should be 1/3 with late fragment tests and 2/4 with early fragment tests. Then it draws over the whole attachment and discards all fragments. (It also atomically writes to a buffer before discarding to force the fragment shader to run.) So I tried to actually fix this by adding a depth attachment in these cases, but no matter what I did (allowing depth writes, enabling the depth test), I couldn't stop Metal from updating the stencil. Weirdly, only half the stencil--the half that wasn't cleared to 1--gets updated, even in cases where I set up the depth test to succeed. In that case, I would've expected both halves to be updated if it were just early fragment tests. Now I'm not even sure it's that. I think this might actually be a bug in Metal itself. Maybe the Apple Silicon driver *always* runs stencil tests early.

I do wonder if the spec might be too loose and/or unclear, particularly around the behavior of the `FragDepth` builtin and early/late fragment tests.

**Comment by aitor-lunarg** [comment]
Do we know the revisions of MoltenVK and CTS this was tested on? Hardware and driver version?

The test passes for me on an M3 with latest vulkan-cts-1.3.8 and MoltenVK

**Comment by billhollings** [comment]
Two years old for everything, that's certain.

It's passing for me under the same conditions. Interesting. Possibly one or both of Metal and CTS have been modified so that it is no longer an issue.

For now, we can ignore this issue, then. I see you have it marked in the spreadsheet similarly.

**Comment by aitor-lunarg** [comment]
Issue is no longer present. There's a new similar test that got flagged as this one in the spreadsheet called `dEQP-VK.fragment_operations.early_fragment.discard_no_early_fragment_tests_depth`. I will create a new issue if required.
