### ISSUE TITLE
MoltenVK Vulkan 1.0: Point polygon fill mode and depth bias

### ISSUE THREAD

**Issue by aitor-lunarg** [KhronosGroup/Vulkan-Portability#65]
Failing CTS tests:
```
dEQP-VK.draw.renderpass.depth_bias.depth_bias_triangle_list_point
```

The test renders a triangle list with points as polygon fill mode. However, Metal does not support fill mode to be points (https://developer.apple.com/documentation/metal/mtltrianglefillmode), so MoltenVK decides to change the input primitive topology type to point instead of triangle list. This seems like a reasonable approach. However, Metal does not support depth bias unless the topology type is triangles (https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1516269-setdepthbias check note). Due to this combination the test fails.

Proposed solutions:
 - Disable non solid polygon fill mode. Due to Vulkan coupling point and line polygon fill modes into `VkPhysicalDeviceFeatures::fillModeNonSolid` we would also lose line fill mode when Metal does support this.
 - Flag in `VK_KHR_portability_subset_metal` to let the user know that point fill mode is not allowed.
 - Flag in `VK_KHR_portability_subset_metal` to let the user know that depth bias is not supported when polygon fill mode is point.
 - Waiver

Let me know your thoughts or if I missed anything.

**Comment by lexaknyazev** [comment]
The original portability subset extension had the `pointPolygons` flag (https://github.com/KhronosGroup/MoltenVK/issues/1396). It was recently renamed to `rasterizationDynamicPolygonModePoints` assuming that emulation is feasible (see discussions in https://github.com/KhronosGroup/MoltenVK/pull/2100).

**Comment by aitor-lunarg** [comment]
Thank you for pointing it out! I was not aware of that flag, I'll close the issue
